version: '3'

services:
  mysql:
    container_name: liminha-db_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=keycloak_db
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/mysql:/var/lib/mysql
    # networks:
    #   - my-network

  keycloak:
    container_name: liminha-keycloak
    build: ./keycloak/
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB=mysql
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_URL=jdbc:mysql://localhost:3306/keycloak_db
      - HOSTNAME=localhost
    ports:
      - 8080:8080
    depends_on:
      - mysql
    # networks:
    #   - my-network

  nest:
    container_name: liminha-nest
    build: ./nest/
    environment:
      - CLIENT_SECRET=R6I6DzJ8auh7krPZCkzcwKGEgvAFgifV
    ports:
      - 3000:3000
    # extra_hosts:
    # - "host.docker.internal:host-gateway"

  react:
    container_name: liminha-react
    build: ./react/
    ports:
      - 5173:5173

# networks:
#   my-network: